### ISSUE TITLE
How does it works?

### ISSUE THREAD

**Issue by Altamash347** [Xenophilicy/Decorations#1]
can you tell me the whole proceedure how to use it and i cant download it from here https://poggit.pmmp.io/ci/Xenophilicy/Decorations/Decorations

![image](https://user-images.githubusercontent.com/66252903/92078575-f442ee00-edd7-11ea-9e0f-d322d14d9284.png)

**Comment by Xenophilicy** [comment]
The plugin is nowhere near complete, it's still under development
